### ISSUE TITLE
Where build release 

### ISSUE THREAD

**Issue by QPLAYid** [Xposed-Modules-Repo/me.hd.hookwzry#1]
Where build release for download ?

**Comment by HdShare** [comment]
The latitude and longitude are fixed now, and when I complete and fix it, I can download it, and I expect it to be within a week

**Comment by QPLAYid** [comment]
> The latitude and longitude are fixed now, and when I complete and fix it, I can download it, and I expect it to be within a week

Are you interested in modmenu? Recently I saw a lot of people using modmenu such as LG Modmenu but there is no xposed version yet if you are interested can you make an xposed version? thanks

**Comment by HdShare** [comment]
What is modmenu, I don't quite understand

**Comment by QPLAYid** [comment]
> What is modmenu, I don't quite understand

Here 
https://github.com/LGLTeam/Android-Mod-Menu

**Comment by HdShare** [comment]
I'm not very familiar with C and C++, so I don't think there will be any plans for this anytime soon

**Comment by QPLAYid** [comment]
> I'm not very familiar with C and C++, so I don't think there will be any plans for this anytime soon

Oh okay
